// Generated by CoffeeScript 1.7.1
(function() {
  var points_from_detailed_dom, points_from_summary_dom, tools;

  tools = require('./tools');

  points_from_detailed_dom = function(dom) {
    var detail, i, points, tokens;
    try {
      tokens = (function() {
        var _i, _len, _ref, _results;
        _ref = dom('.detail td').get().slice(3);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          i = _ref[_i];
          _results.push(i.children[0].data);
        }
        return _results;
      })();
      points = [];
      while (tokens.length) {
        try {
          detail = tokens.splice(0, 3);
          points.push({
            message: detail[2],
            country_name: detail[1],
            checkpoint_time: tools.utc_date(detail[0])
          });
        } catch (_error) {

        }
      }
      return points;
    } catch (_error) {
      return [];
    }
  };

  points_from_summary_dom = function(dom) {
    var detail, dst, dst_detail, msg, time, token, _i, _len, _ref;
    detail = dom('#clfContent').text().split('\n').slice(29, 31);
    dst_detail = detail[0].trim().split(' - ');
    msg = detail[1];
    dst = null;
    if (dst_detail[0] === "Destination") {
      dst = dst_detail[1];
    }
    time = null;
    _ref = msg.split(' ').reverse();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      token = _ref[_i];
      try {
        time = tools.utc_date(token);
        break;
      } catch (_error) {

      }
    }
    if (!msg) {
      throw new Error('Message not avalible');
    }
    if (!time) {
      time = tools.utc_date('1-Jan-1990');
    }
    return [
      {
        message: msg,
        checkpoint_time: time,
        country_name: dst ? dst : 'not avalible'
      }
    ];
  };

  exports.hkpost = function(tracking_number, callback) {
    var tracking_result, url_4_datail;
    tracking_result = {
      checkpoints: []
    };
    url_4_datail = "http://app3.hongkongpost.hk/CGI/mt/e_detail4.jsp?mail_type=ems_out&tracknbr=" + tracking_number + "&localno=" + tracking_number;
    return tools.request_html_get(url_4_datail, function(error, dom) {
      var points, url_4_summary;
      if (error) {
        return callback(error);
      }
      points = points_from_detailed_dom(dom);
      if (points.length > 0) {
        tracking_result.checkpoints = points.reverse();
        return callback(null, tracking_result);
      }
      url_4_summary = "http://app3.hongkongpost.hk/CGI/mt/mtZresult.jsp?tracknbr=" + tracking_number;
      return tools.request_html_get(url_4_summary, function(error, dom) {
        if (error) {
          return callback(error);
        }
        try {
          tracking_result.checkpoints = points_from_summary_dom(dom);
          return callback(null, tracking_result);
        } catch (_error) {
          error = _error;
          return callback(error);
        }
      });
    });
  };

}).call(this);
