// Generated by CoffeeScript 1.7.1
(function() {
  var exports, get_checkpoint, request, tools, utc_date;

  request = require('request');

  tools = require('./tools');

  utc_date = function(date_string) {
    var date;
    date = new Date(date_string);
    date = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate(), date.getHours(), date.getMinutes(), date.getSeconds()));
    date = date.toISOString();
    return date = date.substring(0, date.length - 5);
  };

  get_checkpoint = function(checkpoint) {
    var date;
    date = utc_date("" + month_date + " " + year + " " + day_time);
    return {
      country_name: '',
      message: message,
      checkpoint_time: date
    };
  };

  exports = function(tracking_number, callback) {
    var tracking_result, url_4_datail, url_4_summary;
    tracking_result = {
      checkpoints: []
    };
    url_4_datail = "http://app3.hongkongpost.hk/CGI/mt/e_detail4.jsp?mail_type=ems_out&tracknbr=" + tracking_number + "&localno=" + tracking_number;
    url_4_summary = "http://app3.hongkongpost.hk/CGI/mt/mtZresult.jsp?tracknbr=" + tracking_number;
    return tools.request_html_get(url_4_summary, function(error, dom) {
      if (error) {
        return callback(error);
      }
    });
  };

  exports('EA999580311HK');

}).call(this);
