// Generated by CoffeeScript 1.7.1
(function() {
  var default_put_callback, logger;

  logger = require('winston');

  logger.remove(logger.transports.Console);

  logger.add(logger.transports.Console, {
    'timestamp': true
  });

  default_put_callback = function(err, jobid) {
    return logger.info("Sent " + jobid + " job");
  };

  exports.put_wrap = function(emitter, tube, priority, delay, ttr, payload, callback) {
    var load;
    if (callback == null) {
      callback = default_put_callback;
    }
    load = {
      type: tube,
      payload: payload
    };
    return emitter.put(priority, delay, ttr, JSON.stringify(load), callback);
  };

}).call(this);
