// Generated by CoffeeScript 1.7.1
(function() {
  var default_put_callback, logger;

  logger = require('winston');

  logger.remove(logger.transports.Console);

  logger.add(logger.transports.Console, {
    'timestamp': true
  });

  default_put_callback = function(tube, payload, delay, ttr, who) {
    return function(err, jobid) {
      return logger.info("\tsent job #" + jobid + " to " + tube + ", " + delay + "s. delay, " + ttr + "s. TTR, payload: " + (JSON.stringify(payload)) + who);
    };
  };

  exports.put_wrap = function(emitter, tube, priority, delay, ttr, payload, who, callback) {
    if (who == null) {
      who = "";
    }
    if (callback == null) {
      callback = null;
    }
    return emitter.use(tube, function(err, tube) {
      var load;
      load = {
        type: tube,
        payload: payload
      };
      if (who !== "") {
        who = ", by " + who;
      }
      if (callback === null) {
        callback = default_put_callback(tube, payload, delay, ttr, who);
      }
      return emitter.put(priority, delay, ttr, JSON.stringify(load), callback);
    });
  };

}).call(this);
