// Generated by CoffeeScript 1.7.1
(function() {
  var beans_tools, emitter, fivebeans, winston;

  fivebeans = require('fivebeans');

  winston = require('winston');

  beans_tools = require('./beans_tools');

  winston.remove(winston.transports.Console);

  winston.add(winston.transports.Console, {
    'timestamp': true
  });

  emitter = new fivebeans.client();

  emitter.on('connect', function() {
    return beans_tools.put_wrap(emitter, 'requests_flow', 0, 0, 60, {
      'slug': 'dpduk',
      'number': '15502370264989N'
    });
  });

  emitter.connect();

}).call(this);
